Use SwiftPackageList to generate acknowledgements.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -9,4 +9,10 @@ then
   exit 1
 fi
 
+swift-package-list ElementX.xcodeproj --requires-license --output-type settings-bundle --output-path ElementX/SupportingFiles
+if ! git diff --quiet -- ./ElementX/SupportingFiles/Settings.bundle || [ -n "$(git ls-files --others --exclude-standard -- ./ElementX/SupportingFiles/Settings.bundle)" ]; then
+  echo "pre-commit: Commit aborted due to unstaged changes to the package Acknowledgements."
+  exit 1
+fi
+
 ./Tools/Scripts/validate_lfs.sh
